In [ ]:
import numpy as np
import pandas as pd
import matplotlib
import altair as alt

In [ ]:
covid = pd.read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv", parse_dates=['date'])
covid.shape

(158858, 67)

In [ ]:
Are the weekly icu admissions related to the the total number of vaccinations in the Netherlands? #This is an interesting question but a bit too difficult
The final research question is going to be: What is the difference in total vaccinations between the Netherlands and Sint Maarten per hundred?

In [ ]:
covid.head()

  iso_code continent  ... excess_mortality excess_mortality_cumulative_per_million
0      AFG      Asia  ...              NaN                                     NaN
1      AFG      Asia  ...              NaN                                     NaN
2      AFG      Asia  ...              NaN                                     NaN
3      AFG      Asia  ...              NaN                                     NaN
4      AFG      Asia  ...              NaN                                     NaN

[5 rows x 67 columns]

In [ ]:
covid.describe()

        total_cases  ...  excess_mortality_cumulative_per_million
count  1.559940e+05  ...                              5460.000000
mean   2.289064e+06  ...                               897.921980
std    1.365934e+07  ...                              1350.138688
min    1.000000e+00  ...                             -1826.595723
25%    1.762000e+03  ...                               -39.908950
50%    2.302600e+04  ...                               422.693140
75%    2.737810e+05  ...                              1527.289615
max    3.816839e+08  ...                              8505.587129

[8 rows x 62 columns]

In [ ]:
covid = covid.rename(columns = {'location' :'Country'}, inplace = False) #renaming the column 'location' to 'Country'

#creating a dataframe with only the columns I require
new_covid = covid[['Country','date','continent', 'population', 'total_vaccinations_per_hundred',]]#Grouping all values by the 'Country' column, choosing the first value from its multiple rows and then reseting the index
new_covid= new_covid.groupby('Country').first().reset_index()#Removing the rows that have na/none in 'continent' column
new_covid=new_covid[new_covid['continent'].notna()].reset_index()#dropping the index column
new_covid= new_covid.drop('index', axis=1)

#dropping the date column
new_covid= new_covid.drop('date', axis=1)#removing spaces at the beginning and at the end
new_covid['Country'] = new_covid['Country'].str.strip()

In [ ]:
new_covid.head(20)

                Country  ... total_vaccinations_per_hundred
0           Afghanistan  ...                           0.00
1               Albania  ...                           0.00
2               Algeria  ...                           0.00
3               Andorra  ...                           0.74
4                Angola  ...                           0.00
5              Anguilla  ...                           0.00
6   Antigua and Barbuda  ...                           0.00
7             Argentina  ...                           0.00
8               Armenia  ...                           0.02
9                 Aruba  ...                          24.04
10            Australia  ...                           0.00
11              Austria  ...                           0.01
12           Azerbaijan  ...                           0.00
13              Bahamas  ...                           0.00
14              Bahrain  ...                           2.23
15           Bangladesh  ...                           0.00
16             Barbados  ...                           1.56
17              Belarus  ...                           0.00
18              Belgium  ...                           0.00
19               Belize  ...                           0.00

[20 rows x 4 columns]

In [ ]:
alt.Chart(new_covid).mark_bar().encode(
    y='total_vaccinations_per_hundred',
    x='Country'
)

alt.Chart(...)

In [ ]:
new_covid.sort_values(by='total_vaccinations_per_hundred', ascending=False)

                             Country  ... total_vaccinations_per_hundred
160                         Pitcairn  ...                         100.00
181        Sint Maarten (Dutch part)  ...                          56.73
28            British Virgin Islands  ...                          49.41
101                           Jersey  ...                          45.27
24   Bonaire Sint Eustatius and Saba  ...                          27.95
..                               ...  ...                            ...
125                 Marshall Islands  ...                            NaN
129             Micronesia (country)  ...                            NaN
153                            Palau  ...                            NaN
170        Saint Pierre and Miquelon  ...                            NaN
218                          Vatican  ...                            NaN

[225 rows x 4 columns]

In [ ]:
new_covid.loc[(new_covid.Country == 'Netherlands') | (new_covid.Country == 'Sint Maarten (Dutch part)'), ]

                       Country  ... total_vaccinations_per_hundred
141                Netherlands  ...                           0.20
181  Sint Maarten (Dutch part)  ...                          56.73

[2 rows x 4 columns]